# Generated by Django 5.2 on 2026-03-28 02:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('quiz_code', models.CharField(editable=False, max_length=10, unique=True)),
                ('timer_mode', models.CharField(choices=[('quiz', 'Quiz Timer Only'), ('question', 'Per-Question Timer Only'), ('both', 'Both Quiz and Question Timers')], default='quiz', max_length=10)),
                ('quiz_duration', models.IntegerField(help_text='Total quiz duration in seconds', validators=[django.core.validators.MinValueValidator(60)])),
                ('pass_mark', models.IntegerField(default=50, help_text='Pass percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('randomize_questions', models.BooleanField(default=True)),
                ('randomize_choices', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'db_table': 'quiz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Easy', 'Section A', 'Hard'", max_length=100)),
                ('marks_per_question', models.IntegerField(default=1, help_text='All questions in this group share the same marks', validators=[django.core.validators.MinValueValidator(1)])),
                ('pick_count', models.IntegerField(help_text='How many questions to randomly pick from this group per student', validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='quiz.quiz')),
            ],
            options={
                'verbose_name': 'Question Group',
                'verbose_name_plural': 'Question Groups',
                'db_table': 'question_group',
                'ordering': ['quiz', 'order'],
                'unique_together': {('quiz', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True/False'), ('calculation', 'Calculation')], default='mcq', max_length=20)),
                ('option_a', models.CharField(blank=True, max_length=500, null=True)),
                ('option_b', models.CharField(blank=True, max_length=500, null=True)),
                ('option_c', models.CharField(blank=True, max_length=500, null=True)),
                ('option_d', models.CharField(blank=True, max_length=500, null=True)),
                ('correct_answer', models.CharField(max_length=500)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Per-question timer (optional)', null=True, validators=[django.core.validators.MinValueValidator(5)])),
                ('max_attempts', models.IntegerField(default=1, help_text='For calculation questions only', validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.IntegerField(default=0)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='quiz.questiongroup')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'question',
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StudentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('reg_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_via', models.CharField(blank=True, choices=[('manual', 'Manual Submission'), ('auto_quiz', 'Auto - Quiz Timer Expired'), ('auto_question', 'Auto - Question Timer Expired')], max_length=20, null=True)),
                ('total_score', models.IntegerField(default=0)),
                ('max_possible_score', models.IntegerField(default=0)),
                ('is_submitted', models.BooleanField(default=False)),
                ('current_question_index', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='quiz.quiz')),
            ],
            options={
                'verbose_name': 'Student Session',
                'verbose_name_plural': 'Student Sessions',
                'db_table': 'student_session',
                'ordering': ['-start_time'],
                'unique_together': {('quiz', 'reg_number')},
            },
        ),
        migrations.CreateModel(
            name='SuspiciousEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('tab_switch', 'Tab Switch'), ('window_blur', 'Window Blur'), ('shortcut_blocked', 'Keyboard Shortcut Blocked'), ('copy_attempt', 'Copy Attempt'), ('paste_attempt', 'Paste Attempt')], max_length=20)),
                ('question_index', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_events', to='quiz.studentsession')),
            ],
            options={
                'verbose_name': 'Suspicious Event',
                'verbose_name_plural': 'Suspicious Events',
                'db_table': 'suspicious_event',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_answer', models.CharField(blank=True, max_length=500, null=True)),
                ('attempts_used', models.IntegerField(default=0)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_awarded', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.studentsession')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'db_table': 'answer',
                'unique_together': {('session', 'question')},
            },
        ),
    ]
