# Generated by Django 5.2 on 2026-06-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_answer_attempts_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsession',
            name='selected_question_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
