# Generated by Django 5.2 on 2026-06-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_studentsession_selected_question_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsession',
            name='teacher_notes',
            field=models.TextField(blank=True, help_text='Internal notes visible to teacher only (Pro feature seed)'),
        ),
    ]
